import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import org.mockito.Mock;

import java.nio.file.Files; //for testing file system
import java.nio.file.Paths;
import java.util.ArrayList;

class FileHandlerTest {
    @Mock private FileHandler fileHandler; //sets up a mockito FileHandler for use in all tests
    @Mock private ArrayList<ArrayList<String>> fileContents; //list of file contents that corresponds to test data folders

    @BeforeEach
    void setUp(){
        fileHandler = new FileHandler();
        fileContents = new ArrayList<>();
        fileContents.add(new ArrayList<>());
        fileContents.add(new ArrayList<>());
        fileContents.getFirst().add("This is a text file. If this is displaying, you were able to access it correctly.");
        fileContents.get(1).add("This is test 2. If you are reading this, you have accessed test2.txt"); //file contents for test1.txt and test2.txt
    }

    @Test
    void readDefaultFiles1() {
        assertNotEquals("Not this", fileHandler.readDefaultFiles());
    }

    @Test
    void readDefaultFiles2(){
        assertNotEquals("Also not this", fileHandler.readDefaultFiles());
    }

    @Test
    void readDefaultFiles3(){ //assert that the file check references a legitimate path
        assertTrue(Files.exists(Paths.get(fileHandler.readDefaultFiles())), "Path generated by defaultFile does not exist.");
    }

    @Test
    void readFile1(){
        assertNull(fileHandler.readFile("")); //test null check for a file path
    }

    @Test
    void readDataFile1(){ //try to read test1.txt
        assertEquals(fileHandler.readFileFromDataFolder("test1.txt"), fileContents.getFirst()); //compare the expected contents of the txt file with the hardcoded valeu
    }
    @Test
    void readDataFile2(){
        assertEquals(fileHandler.readFileFromDataFolder("test2.txt"), fileContents.get(1));
    }
    @Test
    void readNonexistentDataFile(){
        assertNull(fileHandler.readFileFromDataFolder("testNonExistent.txt"));
    }
    @Test
    void testCharIndex1(){
        assertEquals('T', fileHandler.readFileIndexFromData("test1.txt", 0));
    }
    @Test
    void testCharIndex2(){
        assertEquals('h', fileHandler.readFileIndexFromData("test2.txt", 1));
    }
    @Test
    void testNullCharIndex(){
        assertEquals(' ', fileHandler.readFileIndexFromData("test1.txt", 999));
    }
    @Test
    void testNonexistentFile(){
        assertEquals(' ', fileHandler.readFileIndex("fakeFile.txt", 999));
    }
    @Test
    void readDefaultCipherFile(){
        assertEquals('a', fileHandler.readCipherFromID(0).getFirst().toCharArray()[0]);
    }
    @Test
    void readDefaultCipherFileSecondLine(){
        assertEquals('b', fileHandler.readCipherFromID(0).get(1).toCharArray()[0]);
    }
    @Test
    void readNonexistentCipherFile(){
        assertNull(fileHandler.readCipherFromID(999));
    }
    @Test
    void readNegativeIndex(){
        assertNull(fileHandler.readCipherFromID(-1));
    }
    @Test
    void readFileIndex1(){
        assertEquals('f', fileHandler.readCipherFromID(1).get(1).toCharArray()[1]);
    }
    @Test
    void readFileIndex1Again(){
        assertEquals('h', fileHandler.readCipherFromID(1).get(1).toCharArray()[3]);
    }
    @Test
    void checkDataPath(){
        assertNotNull(fileHandler.getDataPath());
    }
}